---
output:  html_document
title: "Is_a_medical_condition"
---

### {.tabset  .tabset-pills}

Here are listed the medical conditions as defined from [SNPedia.](https://www.snpedia.com/index.php/Category:Is_a_medical_condition). Only snps with an allele in SPNedia are reported here.

```{r medical_condition_setup, eval=T, echo=F, include=F}
dir.create(file.path(files_out_dir, "is_a_medical_condition"), recursive=T, showWarnings=F)
my_genotypes_medical_condition <- getMyGenotypeInfoInTopic(my_snps, topic="Is_a_medical_condition", out_dir=data_out_dir, snpedia_data=snpedia_ext_data, force=force_snpedia_update)
my_genotypes_medical_condition_summary <-createDataTableFromGenotypeTagsList(my_genotypes_medical_condition)
```

```{r medical_condition_pages, eval=T, echo=F, include=F}
for (i in 1:10){
  x=my_genotypes_medical_condition[i]
render("files/category_info_page_template.Rmd", params = list(set_title=names(x), genotype_summary=x[[1]] ),
       output_file=file.path(files_out_dir, "is_a_medical_condition", paste0(names(x),".html")), clean=T)
}
```

#### Full table


```{r medical_condition_full_table, eval=T, echo=FALSE,  results='asis'}
my_genotypes_medical_condition_summary_with_links=my_genotypes_medical_condition_summary
category_links <- file.path("file://",files_out_dir, "is_a_medical_condition",paste0(my_genotypes_medical_condition_summary_with_links$Category, ".html"))
my_genotypes_medical_condition_summary_with_links$Category <- paste0("[",my_genotypes_medical_condition_summary_with_links$Category,"](",category_links, ")")

my_genotypes_medical_condition_summary_with_links[1:10,]%>% mutate(
    "Category"=Category,
    "Consequence" = cell_spec(Consequence, "html", color = sapply(Consequence,function(x){switch(as.character(x), "Good"="blue", "Bad"="red", "Unknown"="grey")})),
    "rsid"=rsid,
    "Genotype"=Genotype,
    "Summary"=Summary
  ) %>%
  select("Category", "Consequence", "rsid", "Genotype", "Summary") %>%
kable("html", align = "c", escape = F) %>%
      kable_styling(full_width = T) %>%
  column_spec(1, bold = T) %>%
  collapse_rows(columns = 1:2)

```

#### Searchable table 


```{r medical_condition_searchable_table, eval=T,  echo=F}
datatable(my_genotypes_medical_condition_summary, options = list(pageLength = 50, autoWidth = TRUE))
```
