---
output: html_document
title: "Is_a_medicine"
---

### {.tabset .tabset-fade .tabset-pills}

Here are listed the medicine as defined from [SNPedia.](https://www.snpedia.com/index.php/Category:Is_a_medicine). Only snps with an allele in SPNedia are reported here.

```{r medicine_setup, eval=T,  echo=F}
dir.create(file.path(files_out_dir, "Is_a_medicine"), recursive=T, showWarnings=F)
my_genotypes_medicine <- getMyGenotypeInfoInTopic(my_snps, topic="Is_a_medicine", out_dir=data_out_dir, force=force_snpedia_update)
my_genotypes_medicine_summary <-createDataTableFromGenotypeTagsList(my_genotypes_medicine)
```

```{r medicine_pages, eval=T, echo=F, include=F}
medicine_short_names <- shortenCategoryNames(names(my_genotypes_medicine), max_char=15)
for (i in 1:length(my_genotypes_medicine)){
  x=my_genotypes_medicine[i]
  short_name_x=medicine_short_names[i]
render("files/category_info_page_template.Rmd", params = list(set_title=short_name_x, genotype_summary=x[[1]] ), output_file=file.path(files_out_dir, "Is_a_medicine", paste0(short_name_x,".html")), clean=T)
}
```

#### Full table

```{r medicine_full_table, eval=T, echo=FALSE,  results='asis'}
my_genotypes_medicine_summary_with_links=my_genotypes_medicine_summary
category_links <- file.path("file://",files_out_dir, "Is_a_medicine",paste0(my_genotypes_medicine_summary_with_links$Category, ".html"))
my_genotypes_medicine_summary_with_links$Category <- paste0("[",my_genotypes_medicine_summary_with_links$Category,"](",category_links, ")")

my_genotypes_medicine_summary_with_links%>% mutate(
    "Category"=Category,
    "Consequence" = cell_spec(Consequence, "html", color = sapply(Consequence,function(x){switch(as.character(x), "Good"="blue", "Bad"="red", "Unknown"="grey")})),
    "rsid"=rsid,
    "Genotype"=Genotype,
    "Summary"=Summary
  ) %>%
  select("Category", "Consequence", "rsid", "Genotype", "Summary") %>%
kable( "html", align = "c", escape = F) %>%
      kable_styling(full_width = T) %>%
  column_spec(1, bold = T) %>%
  collapse_rows(columns = 1:2)

```

#### Searchable table

```{r medicine_searchable_table, eval=T, echo=F}
datatable(my_genotypes_medicine_summary, options = list(pageLength = 50, autoWidth = TRUE))
```